#!/usr/bin/env bash

set -o errexit -o pipefail -o noglob -o noclobber -o nounset
IFS=$'\n\t'

export PATH="/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:$PATH"

cd /opt/rails
eval "exec chpst -u rails -- $(ruby -r yaml -e 'puts YAML.load_file("Procfile").fetch("web")')"
